### ISSUE TITLE
missing age and sex for some subjects in participants.tsv

### ISSUE THREAD

**Issue by valosekj** [spine-generic/data-multi-subject#10]
Not all subjects in [participants.tsv](https://github.com/spine-generic/data-multi-subject/blob/master/participants.tsv) file have listed age. Age could be used as a covariate in statistical analysis to rule out potential effect of age on results etc.
Most of subjects with missing age also miss sex.

Sites with missing age:

**institution_id | institution**
- [x] amu | AMU - CEMEREM
- [x] beijing750 | Beijing Tiantan Hospital - sex and age added, date of scan still missing
- [x] beijingPrisma | Beijing Tiantan Hospital - sex and age added, date of scan still missing
- [x] beijingVerio | Beijing Tiantan Hospital - sex and age added, date of scan still missing
- [x] brnoUhb | The University Hospital Brno, Department of Radiology and Nuclear Medicine, Czech Republic
- [x] dresden | Institut_fur_Neuroradiologie, Dresden, Germany
- [x] fslAchieva | Santa Lucia Foundation IRCCS, Rome, Italy
- [x] fslPrisma | Santa Lucia Foundation IRCCS, Rome, Italy - sex and age added, date of scan still missing
- [x] vallHebron | Vall d'Hebron Research Center

**Comment by jcohenadad** [comment]
@alexfoias I've contacted all researchers listed above. In the meantime (when you come back from holidays) if you could look into the raw data, see if you can find that info. Thanks

**Comment by jcohenadad** [comment]
Info for fslAchieva + fslPrisma: [fsl.zip](https://github.com/spine-generic/data-multi-subject/files/5118438/fsl.zip)

**Comment by valosekj** [comment]
> Info for fslAchieva + fslPrisma: [fsl.zip](https://github.com/spine-generic/data-multi-subject/files/5118438/fsl.zip)

Thanks, added into https://github.com/valosekj/data-multi-subject/pull/1. Unfortunately, for fslPrisma subjects, only age and sex were provided (date of scan is still missing).

**Comment by jcohenadad** [comment]
> Thanks, added into valosekj#1. Unfortunately, for fslPrisma subjects, only age and sex were provided (date of scan is still missing).

i've re-sent the email to the researcher

**Comment by jcohenadad** [comment]
@valosekj data for amu: [SOP_Age.xlsx.zip](https://github.com/spine-generic/data-multi-subject/files/5130755/SOP_Age.xlsx.zip)

**Comment by jcohenadad** [comment]
@valosekj for the Beijing sites: [Spine Generic Beijing Clinical Information.xlsx.zip](https://github.com/spine-generic/data-multi-subject/files/5137259/Spine.Generic.Beijing.Clinical.Information.xlsx.zip)

**Comment by valosekj** [comment]
> @valosekj for the Beijing sites: [Spine Generic Beijing Clinical Information.xlsx.zip](https://github.com/spine-generic/data-multi-subject/files/5137259/Spine.Generic.Beijing.Clinical.Information.xlsx.zip)

Thanks 👍 Unfortunately, only sex and age values are included. Date of scan values are missing.

**Comment by jcohenadad** [comment]
> Date of scan values are missing.

is that a problem? i don't think we need this info for our analysis, do we?

**Comment by valosekj** [comment]
> > Date of scan values are missing.
> 
> is that a problem? i don't think we need this info for our analysis, do we?

It is true. Date of scan is not necessary for analysis. Then, provided info is sufficient.

**Comment by jcohenadad** [comment]
@valosekj for vallHebron: [Info_MULTI_SC_BCN.xls.zip](https://github.com/spine-generic/data-multi-subject/files/5151456/Info_MULTI_SC_BCN.xls.zip)

i'd like to make sure that the numbers 1, 2, 3 in the xsl sheet correspond to sub-xx1, sub-xx2, etc.
@alexfoias : can you confirm?

**Comment by valosekj** [comment]
> Info for fslAchieva + fslPrisma: [fsl.zip](https://github.com/spine-generic/data-multi-subject/files/5118438/fsl.zip)

@alexfoias could you please also verify, if number lines corresponds with sub-xx1, sub-xx2, etc. for fslAchieva subjects? I assumed so.

**Comment by alexfoias** [comment]
> @valosekj for vallHebron: [Info_MULTI_SC_BCN.xls.zip](https://github.com/spine-generic/data-multi-subject/files/5151456/Info_MULTI_SC_BCN.xls.zip)
> 
> i'd like to make sure that the numbers 1, 2, 3 in the xsl sheet correspond to sub-xx1, sub-xx2, etc.
> @alexfoias : can you confirm?

Yes, the numbers 1, 2, 3 in the xsl sheet correspond to sub-xx1, sub-xx2, etc.

**Comment by alexfoias** [comment]
> > Info for fslAchieva + fslPrisma: [fsl.zip](https://github.com/spine-generic/data-multi-subject/files/5118438/fsl.zip)
> 
> @alexfoias could you please also verify, if number lines corresponds with sub-xx1, sub-xx2, etc. for fslAchieva subjects? I assumed so.

@valosekj Yes, I checked the number lines corresponds with sub-xx1, sub-xx2, etc. for fslAchieva subjects.

**Comment by jcohenadad** [comment]
@alexfoias info for dresden:
~~~
-          Sub-dresden-01:

o   Sex: f

o   Age: 33

o   Date-of-scan: 2019-04-04

-          Sub-dresden-02:

o   Sex: m

o   Age: 33

o   Date-of-scan: 2019-04-04
~~~
