### ISSUE TITLE
Brain voxels are erased by defacing or out of FOV

### ISSUE THREAD

**Issue by mbondy023** [spine-generic/data-multi-subject#115]
We were interested in obtaining brain volumes of subjects in [spine-generic/data-multi-subject](https://github.com/spine-generic/data-multi-subject) and came across scans with either defacing or FOV issues.

First, the majority of subjects have defacing that extends past the cortex. Erasure occurs in their anterior frontal lobe, anterior temporal lobe, or both. The amount of erasure varies as well, which I have classified in the following categories:
- Few voxels: just a few voxels of gray matter were erased
- Small: just gray matter was erased 
- Medium: gray matter and some of the adjacent white matter erased
- Large: erasure extends beyond white matter tract

The table below describes the number of scans with each issue and a figure for reference:
![Screen Shot 2022-01-27 at 2 17 34 PM](https://user-images.githubusercontent.com/98548430/151437024-60b77d3a-a8d6-4a70-9d74-5dd688c98700.png)

![image](https://user-images.githubusercontent.com/98548430/151433689-1de9cba5-56d9-43e0-bb0c-6548d90da188.png)

Second, some brain were partially out of the FOV during data acquisition. I assume this issue can't be fixed but I thought it was worth noting. Here is a table and figure for reference:
![Screen Shot 2022-01-27 at 2 23 32 PM](https://user-images.githubusercontent.com/98548430/151438130-4fed6c56-0ad5-409b-b9d7-ca04f60c61f7.png)

![image](https://user-images.githubusercontent.com/98548430/151438636-64d1ae1d-7eb7-48d6-bacf-20ed33c54529.png)

Thanks!

**Comment by jcohenadad** [comment]
@mbondy023 thank you very much for reporting this critical issue. Indeed, at the beginning of the project we were mostly focusing on the spinal cord and somewhat "neglected" the brain, especially how the defacing algorithm affected it.

We still have access to some of the non-defaced data, but not all of them. @alexfoias can you please update us?

**Comment by renelabounek** [comment]
@jcohenadad and @alexfoias just a short comment. Monica, Igor and I were discussing that it could be worth to try to contact at least contributors of the 24 T1 images with large erasures, please them to re-deface the images and update the database. + If you have some non-defaced scans, it is perfect partial fix too.

**Comment by jcohenadad** [comment]
@renelabounek great idea. Let's see what we have first (much of the defacing was done by us).

**Comment by alexfoias** [comment]
@jcohenadad @renelabounek I will start comparing what original data we have. I will open a PR with the possible fix.

**Comment by alexfoias** [comment]
I have found an initial version of the dataset non defaced. I will start pushing corrected defaced images.

**Comment by renelabounek** [comment]
@alexfoias, would it help if @mbondy023 shares list of identified subjects with defacing issues? Or would you need some other help from our site?

**Comment by alexfoias** [comment]
@renelabounek yes, I think a list would be helpful.

**Comment by mbondy023** [comment]
@alexfoias Here is a list with the 204 subjects who have only defacing issues. It's not 206 like mentioned above because I took off 2 subjects who have their brains out of the FOV as well.
[DefacingList.xlsx](https://github.com/spine-generic/data-multi-subject/files/8005170/DefacingList.xlsx)

**Comment by renelabounek** [comment]
# T1w RE-DEFACE list:
- [x] sub-amu01
- [x] sub-amu02
- [x] sub-amu03
- [x] sub-amu04
- [x] sub-amu05
- [x] sub-balgrist01
- [x] sub-balgrist02
- [x] sub-balgrist03
- [x] sub-balgrist04
- [x] sub-balgrist06
- [ ] sub-beijingVerio01
- [ ] sub-beijingVerio02
- [ ] sub-beijingVerio04
- [x] sub-brnoCeitec01
- [x] sub-brnoCeitec02
- [x] sub-brnoCeitec03
- [ ] sub-brnoCeitec05
- [ ] sub-brnoCeitec06
- [ ] sub-brnoUhb01
- [ ] sub-brnoUhb02
- [ ] sub-brnoUhb03
- [ ] sub-brnoUhb04
- [ ] sub-brnoUhb05
- [ ] sub-brnoUhb06
- [ ] sub-brnoUhb07
- [ ] sub-brnoUhb08
- [ ] sub-cardiff01
- [ ] sub-cardiff02
- [ ] sub-cardiff03
- [ ] sub-cardiff05
- [ ] sub-cardiff06
- [ ] sub-cmrra01
- [ ] sub-cmrra02
- [ ] sub-cmrra03
- [ ] sub-cmrra04
- [ ] sub-cmrra05
- [ ] sub-cmrra06
- [ ] sub-cmrrb01
- [ ] sub-cmrrb02
- [ ] sub-cmrrb03
- [ ] sub-cmrrb04
- [ ] sub-cmrrb06
- [ ] sub-cmrrb07
- [ ] sub-dresden02
- [ ] sub-fslAchieva02
- [ ] sub-fslAchieva03
- [ ] sub-fslAchieva04
- [ ] sub-fslAchieva05
- [ ] sub-fslAchieva06
- [ ] sub-fslPrisma01
- [ ] sub-fslPrisma02
- [ ] sub-fslPrisma03
- [ ] sub-fslPrisma06
- [ ] sub-geneva01
- [ ] sub-geneva03
- [ ] sub-geneva04
- [ ] sub-geneva05
- [ ] sub-geneva06
- [ ] sub-hamburg01
- [ ] sub-hamburg02
- [ ] sub-hamburg03
- [ ] sub-hamburg04
- [ ] sub-hamburg05
- [ ] sub-hamburg06
- [ ] sub-juntendo750w01
- [ ] sub-juntendo750w02
- [ ] sub-juntendo750w03
- [ ] sub-juntendo750w04
- [ ] sub-juntendo750w05
- [ ] sub-juntendo750w06
- [ ] sub-mgh04
- [ ] sub-mgh05
- [ ] sub-mgh06
- [ ] sub-milan05
- [ ] sub-milan06
- [ ] sub-milan07
- [ ] sub-mniPilot1
- [ ] sub-mniS01
- [ ] sub-mniS02
- [ ] sub-mniS03
- [ ] sub-mniS05
- [ ] sub-mniS06
- [ ] sub-mniS08
- [ ] sub-mountSinai01
- [ ] sub-mountSinai02
- [ ] sub-mountSinai03
- [ ] sub-mountSinai04
- [ ] sub-mountSinai05
- [ ] sub-mountSinai06
- [ ] sub-mpicbs02
- [ ] sub-mpicbs03
- [ ] sub-mpicbs05
- [ ] sub-mpicbs06
- [ ] sub-mpicbs07
- [ ] sub-nottwil01
- [ ] sub-nottwil02
- [ ] sub-nottwil03
- [ ] sub-nottwil04
- [ ] sub-nottwil05
- [ ] sub-nottwil06
- [ ] sub-nwu02
- [ ] sub-nwu03
- [ ] sub-nwu04
- [ ] sub-nwu05
- [ ] sub-nwu06
- [ ] sub-oxfordFmrib01
- [ ] sub-oxfordFmrib02
- [ ] sub-oxfordFmrib03
- [ ] sub-oxfordFmrib04
- [ ] sub-oxfordFmrib05
- [ ] sub-oxfordFmrib06
- [ ] sub-oxfordFmrib08
- [ ] sub-oxfordFmrib09
- [ ] sub-oxfordFmrib10
- [ ] sub-oxfordFmrib11
- [ ] sub-oxfordOhba01
- [ ] sub-oxfordOhba02
- [ ] sub-oxfordOhba04
- [ ] sub-oxfordOhba05
- [ ] sub-pavia01
- [ ] sub-pavia02
- [ ] sub-pavia03
- [ ] sub-pavia04
- [ ] sub-pavia05
- [ ] sub-pavia06
- [ ] sub-perform01
- [ ] sub-perform02
- [ ] sub-perform03
- [ ] sub-perform04
- [ ] sub-perform05
- [ ] sub-perform06
- [ ] sub-queensland01
- [ ] sub-queensland02
- [ ] sub-queensland03
- [ ] sub-queensland05
- [ ] sub-queensland06
- [ ] sub-sherbrooke01
- [ ] sub-sherbrooke04
- [ ] sub-sherbrooke05
- [ ] sub-sherbrooke06
- [ ] sub-sherbrooke07
- [ ] sub-stanford01
- [ ] sub-stanford02
- [ ] sub-stanford03
- [ ] sub-stanford04
- [ ] sub-stanford05
- [ ] sub-stanford06
- [ ] sub-strasbourg02
- [ ] sub-strasbourg03
- [ ] sub-strasbourg05
- [ ] sub-strasbourg06
- [ ] sub-tehranS03
- [ ] sub-tehranS04
- [ ] sub-tehranS05
- [ ] sub-tehranS06
- [ ] sub-tokyo750w01
- [ ] sub-tokyo750w02
- [ ] sub-tokyo750w03
- [ ] sub-tokyo750w04
- [ ] sub-tokyo750w05
- [ ] sub-tokyo750w07
- [ ] sub-tokyoIngenia01
- [ ] sub-tokyoIngenia02
- [ ] sub-tokyoIngenia03
- [ ] sub-tokyoIngenia04
- [ ] sub-tokyoIngenia05
- [ ] sub-tokyoIngenia06
- [ ] sub-tokyoIngenia07
- [ ] sub-tokyoSkyra01
- [ ] sub-tokyoSkyra03
- [ ] sub-tokyoSkyra04
- [ ] sub-tokyoSkyra05
- [ ] sub-tokyoSkyra06
- [ ] sub-tokyoSkyra07
- [ ] sub-ubc01
- [ ] sub-ubc02
- [ ] sub-ubc03
- [ ] sub-ubc04
- [ ] sub-ubc05
- [ ] sub-ubc06
- [ ] sub-ucdavis01
- [ ] sub-ucdavis02
- [ ] sub-ucdavis04
- [ ] sub-ucdavis06
- [ ] sub-unf01
- [ ] sub-unf02
- [ ] sub-unf03
- [ ] sub-unf04
- [ ] sub-unf06
- [ ] sub-unf07
- [ ] sub-vallHebron01
- [ ] sub-vallHebron02
- [ ] sub-vallHebron03
- [ ] sub-vallHebron04
- [ ] sub-vallHebron06
- [ ] sub-vallHebron07
- [ ] sub-vuiisAchieva02
- [ ] sub-vuiisAchieva03
- [ ] sub-vuiisAchieva06
- [ ] sub-vuiisIngenia01
- [ ] sub-vuiisIngenia02
- [ ] sub-vuiisIngenia04
- [ ] sub-vuiisIngenia05
- [ ] sub-vuiisIngenia06

**Comment by renelabounek** [comment]
@alexfoias, I should be able to re-deface cmrra and cmrrb datasets. I do not think you have these data without defacing.

**Comment by kousu** [comment]
@mbondy023, to work around you not being a formal member of this project, please copy-paste this into a comment below. Then you should be able to check off your work as you complete it.

You can click the 'copy' button that appears in the right corner:

![2022-03-11-115326_653x191_scrot](https://user-images.githubusercontent.com/987487/157911914-fb263e9e-1655-409e-9e2d-b144e70448e8.png)


```
# T1w RE-DEFACE list:
- [x] sub-amu01
- [x] sub-amu02
- [x] sub-amu03
- [x] sub-amu04
- [x] sub-amu05
- [x] sub-balgrist01
- [x] sub-balgrist02
- [x] sub-balgrist03
- [x] sub-balgrist04
- [x] sub-balgrist06
- [ ] sub-beijingVerio01
- [ ] sub-beijingVerio02
- [ ] sub-beijingVerio04
- [x] sub-brnoCeitec01
- [x] sub-brnoCeitec02
- [x] sub-brnoCeitec03
- [ ] sub-brnoCeitec05
- [ ] sub-brnoCeitec06
- [ ] sub-brnoUhb01
- [ ] sub-brnoUhb02
- [ ] sub-brnoUhb03
- [ ] sub-brnoUhb04
- [ ] sub-brnoUhb05
- [ ] sub-brnoUhb06
- [ ] sub-brnoUhb07
- [ ] sub-brnoUhb08
- [ ] sub-cardiff01
- [ ] sub-cardiff02
- [ ] sub-cardiff03
- [ ] sub-cardiff05
- [ ] sub-cardiff06
- [ ] sub-cmrra01
- [ ] sub-cmrra02
- [ ] sub-cmrra03
- [ ] sub-cmrra04
- [ ] sub-cmrra05
- [ ] sub-cmrra06
- [ ] sub-cmrrb01
- [ ] sub-cmrrb02
- [ ] sub-cmrrb03
- [ ] sub-cmrrb04
- [ ] sub-cmrrb06
- [ ] sub-cmrrb07
- [ ] sub-dresden02
- [ ] sub-fslAchieva02
- [ ] sub-fslAchieva03
- [ ] sub-fslAchieva04
- [ ] sub-fslAchieva05
- [ ] sub-fslAchieva06
- [ ] sub-fslPrisma01
- [ ] sub-fslPrisma02
- [ ] sub-fslPrisma03
- [ ] sub-fslPrisma06
- [ ] sub-geneva01
- [ ] sub-geneva03
- [ ] sub-geneva04
- [ ] sub-geneva05
- [ ] sub-geneva06
- [ ] sub-hamburg01
- [ ] sub-hamburg02
- [ ] sub-hamburg03
- [ ] sub-hamburg04
- [ ] sub-hamburg05
- [ ] sub-hamburg06
- [ ] sub-juntendo750w01
- [ ] sub-juntendo750w02
- [ ] sub-juntendo750w03
- [ ] sub-juntendo750w04
- [ ] sub-juntendo750w05
- [ ] sub-juntendo750w06
- [ ] sub-mgh04
- [ ] sub-mgh05
- [ ] sub-mgh06
- [ ] sub-milan05
- [ ] sub-milan06
- [ ] sub-milan07
- [ ] sub-mniPilot1
- [ ] sub-mniS01
- [ ] sub-mniS02
- [ ] sub-mniS03
- [ ] sub-mniS05
- [ ] sub-mniS06
- [ ] sub-mniS08
- [ ] sub-mountSinai01
- [ ] sub-mountSinai02
- [ ] sub-mountSinai03
- [ ] sub-mountSinai04
- [ ] sub-mountSinai05
- [ ] sub-mountSinai06
- [ ] sub-mpicbs02
- [ ] sub-mpicbs03
- [ ] sub-mpicbs05
- [ ] sub-mpicbs06
- [ ] sub-mpicbs07
- [ ] sub-nottwil01
- [ ] sub-nottwil02
- [ ] sub-nottwil03
- [ ] sub-nottwil04
- [ ] sub-nottwil05
- [ ] sub-nottwil06
- [ ] sub-nwu02
- [ ] sub-nwu03
- [ ] sub-nwu04
- [ ] sub-nwu05
- [ ] sub-nwu06
- [ ] sub-oxfordFmrib01
- [ ] sub-oxfordFmrib02
- [ ] sub-oxfordFmrib03
- [ ] sub-oxfordFmrib04
- [ ] sub-oxfordFmrib05
- [ ] sub-oxfordFmrib06
- [ ] sub-oxfordFmrib08
- [ ] sub-oxfordFmrib09
- [ ] sub-oxfordFmrib10
- [ ] sub-oxfordFmrib11
- [ ] sub-oxfordOhba01
- [ ] sub-oxfordOhba02
- [ ] sub-oxfordOhba04
- [ ] sub-oxfordOhba05
- [ ] sub-pavia01
- [ ] sub-pavia02
- [ ] sub-pavia03
- [ ] sub-pavia04
- [ ] sub-pavia05
- [ ] sub-pavia06
- [ ] sub-perform01
- [ ] sub-perform02
- [ ] sub-perform03
- [ ] sub-perform04
- [ ] sub-perform05
- [ ] sub-perform06
- [ ] sub-queensland01
- [ ] sub-queensland02
- [ ] sub-queensland03
- [ ] sub-queensland05
- [ ] sub-queensland06
- [ ] sub-sherbrooke01
- [ ] sub-sherbrooke04
- [ ] sub-sherbrooke05
- [ ] sub-sherbrooke06
- [ ] sub-sherbrooke07
- [ ] sub-stanford01
- [ ] sub-stanford02
- [ ] sub-stanford03
- [ ] sub-stanford04
- [ ] sub-stanford05
- [ ] sub-stanford06
- [ ] sub-strasbourg02
- [ ] sub-strasbourg03
- [ ] sub-strasbourg05
- [ ] sub-strasbourg06
- [ ] sub-tehranS03
- [ ] sub-tehranS04
- [ ] sub-tehranS05
- [ ] sub-tehranS06
- [ ] sub-tokyo750w01
- [ ] sub-tokyo750w02
- [ ] sub-tokyo750w03
- [ ] sub-tokyo750w04
- [ ] sub-tokyo750w05
- [ ] sub-tokyo750w07
- [ ] sub-tokyoIngenia01
- [ ] sub-tokyoIngenia02
- [ ] sub-tokyoIngenia03
- [ ] sub-tokyoIngenia04
- [ ] sub-tokyoIngenia05
- [ ] sub-tokyoIngenia06
- [ ] sub-tokyoIngenia07
- [ ] sub-tokyoSkyra01
- [ ] sub-tokyoSkyra03
- [ ] sub-tokyoSkyra04
- [ ] sub-tokyoSkyra05
- [ ] sub-tokyoSkyra06
- [ ] sub-tokyoSkyra07
- [ ] sub-ubc01
- [ ] sub-ubc02
- [ ] sub-ubc03
- [ ] sub-ubc04
- [ ] sub-ubc05
- [ ] sub-ubc06
- [ ] sub-ucdavis01
- [ ] sub-ucdavis02
- [ ] sub-ucdavis04
- [ ] sub-ucdavis06
- [ ] sub-unf01
- [ ] sub-unf02
- [ ] sub-unf03
- [ ] sub-unf04
- [ ] sub-unf06
- [ ] sub-unf07
- [ ] sub-vallHebron01
- [ ] sub-vallHebron02
- [ ] sub-vallHebron03
- [ ] sub-vallHebron04
- [ ] sub-vallHebron06
- [ ] sub-vallHebron07
- [ ] sub-vuiisAchieva02
- [ ] sub-vuiisAchieva03
- [ ] sub-vuiisAchieva06
- [ ] sub-vuiisIngenia01
- [ ] sub-vuiisIngenia02
- [ ] sub-vuiisIngenia04
- [ ] sub-vuiisIngenia05
- [ ] sub-vuiisIngenia06
```

**Comment by mbondy023** [comment]
Thanks @kousu for the help. I've looked over all the scans and updated the list. There are about 70 scans that still have poor defacing, but most have been fixed. 

Importantly, sub-geneva04 was not defaced at all, so that would need to be fixed quickly. 

Edit: Apologies, I missed adding sub-vuiisIngenia03 in our inital list. It also needs to be defaced.

# T1w RE-DEFACE list:
- [x] sub-amu01
- [x] sub-amu02
- [x] sub-amu03
- [x] sub-amu04
- [x] sub-amu05
- [x] sub-balgrist01
- [x] sub-balgrist02
- [x] sub-balgrist03
- [x] sub-balgrist04
- [x] sub-balgrist06
- [ ] sub-beijingVerio01
- [ ] sub-beijingVerio02
- [ ] sub-beijingVerio04
- [x] sub-brnoCeitec01
- [x] sub-brnoCeitec02
- [x] sub-brnoCeitec03
- [x] sub-brnoCeitec05
- [x] sub-brnoCeitec06
- [x] sub-brnoUhb01
- [x] sub-brnoUhb02
- [x] sub-brnoUhb03
- [x] sub-brnoUhb04
- [x] sub-brnoUhb05
- [x] sub-brnoUhb06
- [x] sub-brnoUhb07
- [x] sub-brnoUhb08
- [ ] sub-cardiff01
- [ ] sub-cardiff02
- [ ] sub-cardiff03
- [ ] sub-cardiff05
- [ ] sub-cardiff06
- [x] sub-cmrra01
- [x] sub-cmrra02
- [x] sub-cmrra03
- [x] sub-cmrra04
- [x] sub-cmrra05
- [x] sub-cmrra06
- [x] sub-cmrrb01
- [x] sub-cmrrb02
- [x] sub-cmrrb03
- [x] sub-cmrrb04
- [x] sub-cmrrb06
- [x] sub-cmrrb07
- [x] sub-dresden02
- [ ] sub-fslAchieva02
- [ ] sub-fslAchieva03
- [ ] sub-fslAchieva04
- [ ] sub-fslAchieva05
- [ ] sub-fslAchieva06
- [ ] sub-fslPrisma01
- [ ] sub-fslPrisma02
- [ ] sub-fslPrisma03
- [ ] sub-fslPrisma06
- [x] sub-geneva01
- [x] sub-geneva03
- [x] sub-geneva04
- [x] sub-geneva05
- [x] sub-geneva06
- [ ] sub-hamburg01
- [ ] sub-hamburg02
- [ ] sub-hamburg03
- [ ] sub-hamburg04
- [ ] sub-hamburg05
- [ ] sub-hamburg06
- [x] sub-juntendo750w01
- [x] sub-juntendo750w02
- [x] sub-juntendo750w03
- [x] sub-juntendo750w04
- [x] sub-juntendo750w05
- [x] sub-juntendo750w06
- [ ] sub-mgh04
- [ ] sub-mgh05
- [ ] sub-mgh06
- [ ] sub-milan05
- [ ] sub-milan06
- [ ] sub-milan07
- [ ] sub-mniPilot1
- [ ] sub-mniS01
- [ ] sub-mniS02
- [ ] sub-mniS03
- [ ] sub-mniS05
- [ ] sub-mniS06
- [ ] sub-mniS08
- [ ] sub-mountSinai01
- [ ] sub-mountSinai02
- [ ] sub-mountSinai03
- [ ] sub-mountSinai04
- [ ] sub-mountSinai05
- [ ] sub-mountSinai06
- [ ] sub-mpicbs02
- [ ] sub-mpicbs03
- [ ] sub-mpicbs05
- [ ] sub-mpicbs06
- [ ] sub-mpicbs07
- [x] sub-nottwil01
- [x] sub-nottwil02
- [x] sub-nottwil03
- [x] sub-nottwil04
- [x] sub-nottwil05
- [x] sub-nottwil06
- [x] sub-nwu02
- [x] sub-nwu03
- [x] sub-nwu04
- [x] sub-nwu05
- [x] sub-nwu06
- [x] sub-oxfordFmrib01
- [x] sub-oxfordFmrib02
- [x] sub-oxfordFmrib03
- [x] sub-oxfordFmrib04
- [x] sub-oxfordFmrib05
- [x] sub-oxfordFmrib06
- [x] sub-oxfordFmrib08
- [x] sub-oxfordFmrib09
- [x] sub-oxfordFmrib10
- [x] sub-oxfordFmrib11
- [x] sub-oxfordOhba01
- [x] sub-oxfordOhba02
- [x] sub-oxfordOhba04
- [x] sub-oxfordOhba05
- [x] sub-pavia01
- [ ] sub-pavia02
- [ ] sub-pavia03
- [ ] sub-pavia04
- [ ] sub-pavia05
- [ ] sub-pavia06
- [x] sub-perform01
- [x] sub-perform02
- [x] sub-perform03
- [x] sub-perform04
- [x] sub-perform05
- [x] sub-perform06
- [x] sub-queensland01
- [x] sub-queensland02
- [x] sub-queensland03
- [x] sub-queensland05
- [x] sub-queensland06
- [x] sub-sherbrooke01
- [x] sub-sherbrooke04
- [x] sub-sherbrooke05
- [x] sub-sherbrooke06
- [x] sub-sherbrooke07
- [x] sub-stanford01
- [x] sub-stanford02
- [x] sub-stanford03
- [x] sub-stanford04
- [x] sub-stanford05
- [x] sub-stanford06
- [x] sub-strasbourg02
- [x] sub-strasbourg03
- [x] sub-strasbourg05
- [x] sub-strasbourg06
- [ ] sub-tehranS03
- [ ] sub-tehranS04
- [ ] sub-tehranS05
- [ ] sub-tehranS06
- [x] sub-tokyo750w01
- [x] sub-tokyo750w02
- [x] sub-tokyo750w03
- [x] sub-tokyo750w04
- [x] sub-tokyo750w05
- [x] sub-tokyo750w07
- [x] sub-tokyoIngenia01
- [x] sub-tokyoIngenia02
- [x] sub-tokyoIngenia03
- [x] sub-tokyoIngenia04
- [x] sub-tokyoIngenia05
- [x] sub-tokyoIngenia06
- [x] sub-tokyoIngenia07
- [x] sub-tokyoSkyra01
- [x] sub-tokyoSkyra03
- [x] sub-tokyoSkyra04
- [x] sub-tokyoSkyra05
- [x] sub-tokyoSkyra06
- [x] sub-tokyoSkyra07
- [x] sub-ubc01
- [x] sub-ubc02
- [x] sub-ubc03
- [x] sub-ubc04
- [x] sub-ubc05
- [x] sub-ubc06
- [ ] sub-ucdavis01
- [ ] sub-ucdavis02
- [ ] sub-ucdavis04
- [ ] sub-ucdavis06
- [x] sub-unf01
- [x] sub-unf02
- [x] sub-unf03
- [x] sub-unf04
- [x] sub-unf06
- [x] sub-unf07
- [x] sub-vallHebron01
- [x] sub-vallHebron02
- [x] sub-vallHebron03
- [x] sub-vallHebron04
- [x] sub-vallHebron06
- [x] sub-vallHebron07
- [x] sub-vuiisAchieva02
- [x] sub-vuiisAchieva03
- [x] sub-vuiisAchieva06
- [x] sub-vuiisIngenia01
- [x] sub-vuiisIngenia02
- [ ] sub-vuiisIngenia03
- [x] sub-vuiisIngenia04
- [x] sub-vuiisIngenia05
- [x] sub-vuiisIngenia06

**Comment by alexfoias** [comment]
@mbondy023 thanks for the heads up about `sub-geneva04`. I have fixed it in https://github.com/spine-generic/data-multi-subject/pull/119/commits/8797ed2009253a7d6f6a89c6bd1925e5515b8a66
