### ISSUE TITLE
Fix filenames for MTS

### ISSUE THREAD

**Issue by alexfoias** [spine-generic/data-multi-subject#116]
MTS scans should be follow the specs as in the dataset - `qmri_mtsat`: https://github.com/bids-standard/bids-examples/tree/master/qmri_mtsat/sub-01/anat

```
acq-MTon_MTS → flip-1_mt-on_MTS
acq-MToff_MTS → flip-1_mt-off_MTS
acq-T1w_MTS → flip-2_mt-off_MTS
```

**Comment by valosekj** [comment]
Done in https://github.com/spine-generic/data-multi-subject/pull/135.
