### ISSUE TITLE
Unable to access these remotes: amazon

### ISSUE THREAD

**Issue by dyollb** [spine-generic/data-multi-subject#132]
I am trying to download some of the data but am getting similar issues as in #107.
I have git-annex 10.20220822 installed. Running MacOS 12.6.

> data-multi-subject % git annex get sub-nwu01
> get sub-nwu01/anat/sub-nwu01_T1w.nii.gz (from amazon...) 
> 
>   S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3
> 
>   cannot download content
> 
>   Unable to access these remotes: amazon
> 
>   Maybe add some of these git remotes (git remote add ...):
>   	e405e14e-33b2-4a35-b7a7-3eeec054f0d4 -- sebeda@joplin.neuro.polymtl.ca:/mnt/nvme/sebeda/data-multi-subject
>    	fc75435d-eb11-4c5a-9b68-debf6e68df2a -- alex@MacBook.local:~/data/data-multi-subject
> 
>   (Note that these git remotes have annex-ignore set: origin)
> failed
> (from amazon...) t/sub-nwu01_T2star.nii.gz 

The output of `git remote -v` is:
> amazon	
> origin	https://github.com/spine-generic/data-multi-subject (fetch)
> origin	https://github.com/spine-generic/data-multi-subject (push)

Should I follow the advice and add one of the remotes mentioned above?

**Comment by mguaypaq** [comment]
Thanks for reporting this issue. Based on this part of the error message, it looks like we currently have the `amazon` remote misconfigured:

> S3 bucket does not allow public access; Set both AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to use S3

Indeed, I was able to reproduce the issue locally, and the `amazon` remote wrongly has the setting `public=no`. I've reset it to `public=yes`, so it should work now, as long as you run this command first:

```
git fetch origin
git annex get sub-nwu01
```

To answer your other question:

> Should I follow the advice and add one of the remotes mentioned above?

No, these remotes are an internal server, and someone's laptop, neither of which is accessible from the internet, so they wouldn't work. It's an unfortunate side-effect of how git-annex works that these details are visible to you.

(Internal note: this is related to #122, in particular [this comment](https://github.com/spine-generic/data-multi-subject/issues/122#issuecomment-1193029479) might help us avoid the issue in the future.)

**Comment by dyollb** [comment]
thanks! it works now.
