### ISSUE TITLE
Two T1w labels for some subjects

### ISSUE THREAD

**Issue by valosekj** [spine-generic/data-multi-subject#147]
@NathanMolinier and I noticed that some subjects have duplicated T1w labels:

```console
data-multi-subject/derivatives/labels/sub-amu02/anat$ ls -1 *T1w*labels*nii.gz
sub-amu02_T1w_RPI_r_labels-manual.nii.gz
sub-amu02_T1w_labels-disc-manual.nii.gz
```

### `T1w_RPI_r_labels-manual.nii.gz`
These labels were created in the context of the spine-generic paper on the reoriented and resampled images (see lines [here](https://github.com/spine-generic/spine-generic/blob/c8c8408715f101414ca08c6bcf29a5d5b87df90a/process_data.sh#L149-L151)). These files contain only two labels at C3 and C5 **_mid-vertebral levels_** (because we used only two labels for the registration to the template), see lines [here](https://github.com/spine-generic/spine-generic/blob/c8c8408715f101414ca08c6bcf29a5d5b87df90a/process_data.sh#L71-L72). These labels are available only for 31 subjects (those where the automatic labeling did not work).

### `T1w_labels-disc-manual.nii.gz`
These labels were created manually by @NathanMolinier using the `manual-correction.py` script in the original images (i.e., no reorientation and resampling were applied). These files contain **_disc labels_** for all visible discs. These labels are available for **_all_** the subjects.

---

@NathanMolinier pointed out that it might be confusing to have two "labels" files.

Potential solutions: 
- clarify the difference between the label files in README.md
- suggestion from @NathanMolinier: remove `T1w_RPI_r_labels-manual.nii.gz` files

Related to https://github.com/spine-generic/data-multi-subject/issues/95

**Comment by mguaypaq** [comment]
It sounds like the two kinds of label files should be in two separate derivatives, each with their own README (which can just be your two paragraphs from this issue description!). Maybe `derivatives/vertebral-labels/` and `derivatives/disc-labels/`?

**Comment by valosekj** [comment]
> It sounds like the two kinds of label files should be in two separate derivatives, each with their own README (which can just be your two paragraphs from this issue description!).

Yeah, this would make sense. 

>  Maybe `derivatives/vertebral-labels/` and `derivatives/disc-labels/`?

I initially thought that we could keep the `T1w_RPI_r_labels-manual.nii.gz` files under the current `derivatives/labels/` folder to keep them together with other files created using the same analysis script [process_data.sh](https://github.com/spine-generic/spine-generic/blob/master/process_data.sh) and move the `T1w_labels-disc-manual.nii.gz` files created by @NathanMolinier to a new `derivatives/disc-labels/` folder.

But the tricky thing is that Nathan just updated/corrected the `T1w_labels-disc-manual.nii.gz` files which already had been living beside `T1w_RPI_r_labels-manual.nii.gz` under `derivatives/labels/` for a long time.

---

Sidenote: I will also upload soon spinal nerve rootlets segmentations created in the context of the [model-spinal-rootlets](https://github.com/ivadomed/model-spinal-rootlets) project. I guess a good strategy would be to save them under a new folder like `derivatives/spinal-rootlets-labels/`.
