### ISSUE TITLE
Labels with missing suffixes

### ISSUE THREAD

**Issue by NathanMolinier** [spine-generic/data-multi-subject#151]
## Description

I noticed that for some subjects masks, suffixes are missing:
- derivatives/labels_softseg/sub-brnoCeitec01/anat/sub-brnoCeitec01_T1w.nii.gz
- derivatives/labels_softseg/sub-barcelona02/anat/sub-barcelona02_flip-1_mt-on_MTS.nii.gz
- derivatives/labels_softseg/sub-barcelona02/anat/sub-barcelona02_T2w.nii.gz
- derivatives/labels_softseg/sub-balgrist02/anat/sub-balgrist02_flip-1_mt-on_MTS.nii.gz

@sandrinebedard should we just add `_softseg` ?

**Comment by sandrinebedard** [comment]
yes!

**Comment by NathanMolinier** [comment]
@sandrinebedard it seems that the problem is different actually. The two files with and without the suffix `_softseg` are present in the derivatives folders and they both represent soft segmentations of the spinal cord with different soft values. What should I do with these files ?

tagging @valosekj if you have any suggestions

**Comment by sandrinebedard** [comment]
I would keep the softseg one!
