### ISSUE TITLE
Add processed images in the derivatives folder

### ISSUE THREAD

**Issue by sandrinebedard** [spine-generic/data-multi-subject#156]
## Description
Since the labels in the derivatives were generated from preprocessed images (reorientation, resampling, etc.), to avoide confusion and issues such as #153 and repeating these steps, we propose to include the preprocessed images inside the derivatives folder in a sub-folder. 

## Suggestion
* Add the preprocessed images in : `derivatives/processed_data`  (we can discuss on better names)
* Include in the README of `derivatives/processed_data` a link to a release of the dataset and preprocessing script used to create these images

## Tasks:

* add dataset description
* add readme (and link to processing script)
* add suffix `space-other`
* add suffix description `space-other `in all json 
* create json sidecar for dwi rec-average
## Relevant issues:

#144
#153

**Comment by sandrinebedard** [comment]
tagging @jcohenadad @valosekj @mguaypaq @NathanMolinier

**Comment by NathanMolinier** [comment]
Agree with this proposal ! Also, from a more technical standpoint, to follow our conventions, the entity `space-other` should be added to the filename as well as a JSON sidecar file. Examples are shown [here](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#json-sidecars).

**Comment by sandrinebedard** [comment]
> Agree with this proposal ! Also, from a more technical standpoint, to follow our conventions, the entity `space-other` should be added to the filename as well as a JSON sidecar file. Examples are shown [here](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#json-sidecars).

would we also add it in all the labels too?

**Comment by NathanMolinier** [comment]
Yes we should do that also

**Comment by jcohenadad** [comment]
My two cents:
- agreed with adding `space-other` to minimize confusion about the labels' native space
- given that the data are only resampled/reoriented maybe we should call it `data_preprocessed` instead?
- i would add the software used to preprocess the data (as done in BIDS Apps), eg: `data_preprocessed_sct6.0`
