### ISSUE TITLE
Refractor derivatives naming convention

### ISSUE THREAD

**Issue by sandrinebedard** [spine-generic/data-multi-subject#157]
## Description
Since we have now [clarified ](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#building-the-derivatives-datasets)the naming of the labels in the derivatives, we need to update the derivatives name in spine generic

## Suggestions

* `sub-amu01_T2star_seg-manual.nii.gz` --> `sub-amu01_T2star_label-SC_seg.nii.gz`
* `sub-amu01_T2w_labels-disc-manual.nii.gz` --> `sub-amu01_T2w_label-discs_dlabel.nii.gz`
* `sub-amu01_T1w_softseg.nii.gz` --> `sub-amu01_T1w_label-SC_softseg.nii.gz`
* `sub-amu01_T1w_softseg_bin.nii.gz` --> `sub-amu01_T1w_desc-softseg_label-SC_seg.nii.gz`  (to be discussed)
* `sub-amu01_T1w_csfseg-manual.nii.gz` --> `sub-amu01_T1w_label-CSF_seg.nii.gz`
* For discs warped from T2w: `sub-amu01_T2w_label-discs_desc-warp_dlabel.nii.gz`
* `_RPI_r_labels-manual` --> `space-other_T2w_label-vertebrae_desc-C2C5_dlabel`
* `gmseg `--> `label-GM_seg`

**Note**: do we want to add the discs labels from warping from T2w for the other contrasts inside the derivatives? (as we do and need for the contrast-agnostic project)

## Related issues
#156 
#154
#141

## TODO

* Update all preprocessing scripts with new name convention

**Comment by sandrinebedard** [comment]
tagging @jcohenadad @valosekj @mguaypaq @NathanMolinier

**Comment by jcohenadad** [comment]
![image](https://github.com/spine-generic/data-multi-subject/assets/2482071/a15924cf-5515-4340-8c4a-c13ea9eb6e81)

Looks good to me! (i'm copy/pasting in case the issue text changes in the future)

> Note: do we want to add the discs labels from warping from T2w for the other contrasts inside the derivatives? (as we do and need for the contrast-agnostic project)

I would say yes, so that the contrast-agnostic model can more easily be reproduced, no?

**Comment by naga-karthik** [comment]
> so that the contrast-agnostic model can more easily be reproduced, no?

Yes! We required the disc labels for vertebral labeling and the C2-C3 CSA computation via `sct_process_segmentation`. Hence, adding the disc labels would be good!

**Comment by sandrinebedard** [comment]
@NathanMolinier 

We have some disc labels that are warped from the T2w, but we want to add them in the derivatives 2 (BUT THEY MAY NOT BE PERFECT) and we do not want to be confused between them and manual disc labels, do you have a suggetsion?

**Comment by jcohenadad** [comment]
We should also add the `space-other` field https://github.com/spine-generic/data-multi-subject/issues/156

**Comment by sandrinebedard** [comment]
I noticed that the  disc labels in the derivatives are in the original space LPI, should I reorient them and add `space-other` to be consitent? or do we keep them in the original space?

**Comment by NathanMolinier** [comment]
> We should also add the `space-other` field #156

Or `space-warp` but we need to add this to the JSON sidecar as well to say that the image was warped from another contrast

**Comment by NathanMolinier** [comment]
> I noticed that the disc labels in the derivatives are in the original space LPI, should I reorient them and add `space-other` to be consitent? or do we keep them in the original space?

Therefore, do we need to store 2 versions of the discs labels ?

**Comment by sandrinebedard** [comment]
reorientation is a very simple step, I don't think we need 2 versions (in the contrast-agnsotic pipeline, sct_label_vertebrae reorients in any case)
