### ISSUE TITLE
same participants on different scanners

### ISSUE THREAD

**Issue by bpinsard** [spine-generic/data-multi-subject#166]
It seems from demographics/weight that some site with multiple scanners (eg. beijing) acquired the same participants on multiple scanners, but are stored as different participants, is this documented?

It is related to #102 

It could greatly influence results depending on the type of analysis one want to run.

**Comment by jcohenadad** [comment]
Thank you for catching this @bpinsard. I'm closing this issue since it's a duplicate, but added a comment to revive the issue https://github.com/spine-generic/data-multi-subject/issues/102#issuecomment-2106296535
