### ISSUE TITLE
CI timeout error

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/data-multi-subject#21]
For ~2 weeks now, the test on Travis does not pass anymore. See eg [this recent build](https://travis-ci.com/github/spine-generic/data-multi-subject/builds/181667371):

~~~
$ echo -e "\e[1m \e[4m \e[34mDownloading dataset; this will take a while. \n"
  Downloading dataset; this will take a while. 
740.20s$ travis_wait 20 git annex get -J 2 -q
The command git annex get -J 2 -q exited with 1.
Log:
git-annex: get: 5 failed
/home/travis/.travis/functions: line 607:  8437 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
The command "travis_wait 20 git annex get -J 2 -q" failed and exited with 1 during .
Your build has been stopped.
~~~

**Comment by jcohenadad** [comment]
Weirdly, the runtime indicated on Travis is 740s (~12min), whereas the `travis_wait 20` should give us 20min.

**Comment by lrouhier** [comment]
maybe we should put it before calling travis.sh?
like  "SCRIPT="travis_wait 60 travis.sh" (from https://github.com/cyberFund/cybernode-archive/commit/177cace4949e02def66dd7f36c4dac5bc3c2dd66)

**Comment by jcohenadad** [comment]
possibly related: https://github.com/datalad/datalad/issues/12

but likely not, because a previous build used the same version of git-annex and passed https://travis-ci.com/github/spine-generic/data-multi-subject/jobs/378457629#L562

**Comment by jcohenadad** [comment]
> maybe we should put it before calling travis.sh?

@lrouhier not sure what travis.sh you are referring to?

**Comment by lrouhier** [comment]
Ah My bad I thought that it was similar to spine generic (where we call an external script). Maybe as the first command in the install?

**Comment by jcohenadad** [comment]
ah! setting travis_wait from 20 to 60 solved it 🎉 
https://travis-ci.com/github/spine-generic/data-multi-subject/builds/181697199#L562

**Comment by jcohenadad** [comment]
Fixed by https://github.com/spine-generic/data-multi-subject/pull/22
