### ISSUE TITLE
Implement CI that checks files & participants.tsv

### ISSUE THREAD

**Issue by alexfoias** [spine-generic/data-multi-subject#28]
The idea is to check the subjects listed in participants.tsv and the actual data sub-* data. This check will be done also the other way from data folders again the tsv file.

**Comment by jcohenadad** [comment]
@alexfoias is that implemented?

**Comment by alexfoias** [comment]
It was implemented here: https://github.com/spine-generic/spine-generic/issues/170

We can close the issue
