### ISSUE TITLE
Processing issues in r20200830: GM and MTS segmentation

### ISSUE THREAD

**Issue by valosekj** [spine-generic/data-multi-subject#35]
Here, I list data quality issues related to [r20200830](https://github.com/spine-generic/data-multi-subject/releases/tag/r20200830) release.

I focused on outliers in generated figures by `sq_generate_figures.py`.

So far, I found problems with MT SC segmentations:

<details><summary>Bad SC segmentation sub-fslAchieva03_acq-T1w_MTS_seg.nii.gz</summary>
<img width="946" alt="image" src="https://user-images.githubusercontent.com/39456460/91747306-9a1f0e80-ebc6-11ea-9f4c-8cc8ef9a3174.png">
</details>

<details><summary>Bad SC segmentation sub-fslAchieva04_acq-T1w_MTS_seg.nii.gz</summary>
<img width="943" alt="image" src="https://user-images.githubusercontent.com/39456460/91747358-b58a1980-ebc6-11ea-9047-ccfee8777196.png">
</details>

<details><summary>Bad SC segmentation sub-fslAchieva05_acq-T1w_MTS_seg.nii.gz</summary>
<img width="948" alt="image" src="https://user-images.githubusercontent.com/39456460/91747404-cd619d80-ebc6-11ea-8913-30126468643d.png">
</details>

<details><summary>Bad SC segmentation sub-fslAchieva06_acq-T1w_MTS_seg.nii.gz</summary>
<img width="950" alt="image" src="https://user-images.githubusercontent.com/39456460/91747152-617f3500-ebc6-11ea-911d-cf0b43130c9c.png">
</details>

And GM segmentation issues:

<details><summary>Bad GM segmentation sub-fslAchieva04_T2star_rms_gmseg.nii.gz</summary>
<img width="945" alt="image" src="https://user-images.githubusercontent.com/39456460/91748761-27fbf900-ebc9-11ea-868f-20f0fde6a280.png">
</details>

<details><summary>Missing GM segmentation in a few slices sub-tokyoIngenia04_T2star_rms_gmseg.nii.gz</summary>
<img width="944" alt="image" src="https://user-images.githubusercontent.com/39456460/91748988-8923cc80-ebc9-11ea-8079-83aaee070c3f.png">
</details>

**Comment by evaalonsoortiz** [comment]
From the figures I generated, I identified the following outliers:

<details>
<summary>MTR: geneva02</summary>
<br>
QC images do not show any obvious segmentation or labeling errors
<img width="777" alt="Screen Shot 2020-08-31 at 1 49 18 PM" src="https://user-images.githubusercontent.com/6652194/91750254-c881f700-eb90-11ea-9cd5-467e6cafa0e8.png">
<img width="1255" alt="Screen Shot 2020-08-31 at 1 51 25 PM" src="https://user-images.githubusercontent.com/6652194/91750426-14cd3700-eb91-11ea-9617-91d52550dc85.png">
</details>
<details>
<summary>CSA-T2w: sub-oxfordFmrib04</summary>
<br>
QC images do not show any obvious segmentation or labeling errors
<img width="742" alt="Screen Shot 2020-08-31 at 1 47 58 PM" src="https://user-images.githubusercontent.com/6652194/91750171-a1c3c080-eb90-11ea-8ceb-90b26000b12a.png">
<img width="1251" alt="Screen Shot 2020-08-31 at 1 46 24 PM" src="https://user-images.githubusercontent.com/6652194/91750100-85278880-eb90-11ea-8a61-30fa0aca280e.png">
</details>

**Comment by jcohenadad** [comment]
> CSA-T2w: sub-oxfordFmrib04: the subject was supposed to be excluded from the stats: https://github.com/spine-generic/data-multi-subject/blob/master/exclude.yml#L5

@evaalonsoortiz was it included in the figure generation (in that case it's a bug)?

same thing for geneva02/mtr: https://github.com/spine-generic/data-multi-subject/blob/master/exclude.yml#L14

**Comment by jcohenadad** [comment]
> Bad GM segmentation sub-fslAchieva04_T2star_rms_gmseg.nii.gz

--> need to exclude

**Comment by jcohenadad** [comment]
@valosekj @evaalonsoortiz can you please move the list of data quality issue to the [specific issue with respective contrast](https://github.com/spine-generic/data-multi-subject/issues?q=is%3Aopen+is%3Aissue+label%3A%22data+quality%22) (create one if does not exist). The purpose of these "data-quality" issue are to gather all problems with data quality. It is *not* specific to a release (ie no relation with the processing).  However, if there are new subjects to exclude for the analysis/figure, please start a branch to modify the `exclude.yml` file. Thanks!

**Comment by evaalonsoortiz** [comment]
> > CSA-T2w: sub-oxfordFmrib04: the subject was supposed to be excluded from the stats: https://github.com/spine-generic/data-multi-subject/blob/master/exclude.yml#L5
> 
> @evaalonsoortiz was it included in the figure generation (in that case it's a bug)?
> 
> same thing for geneva02/mtr: https://github.com/spine-generic/data-multi-subject/blob/master/exclude.yml#L14

Ah, no my bad. I did not exclude any subjects, I had assumed those were excluded when the processing step is taken.

**Comment by jcohenadad** [comment]
GM seg to fix:
![image](https://user-images.githubusercontent.com/2482071/91923134-98744a00-ec9d-11ea-8d7f-333e6abef998.png)
![image](https://user-images.githubusercontent.com/2482071/91923261-ebe69800-ec9d-11ea-8801-0da1667d3f64.png)
![image](https://user-images.githubusercontent.com/2482071/91923465-6c0cfd80-ec9e-11ea-9163-765626b24625.png)
![image](https://user-images.githubusercontent.com/2482071/91923437-5d264b00-ec9e-11ea-94e2-3a5e73d6c08f.png)
![image](https://user-images.githubusercontent.com/2482071/91923399-45e75d80-ec9e-11ea-8ee5-4a5aff14b223.png)

**Comment by jcohenadad** [comment]
GM segmentation fixed in https://github.com/spine-generic/data-multi-subject/pull/40

**Comment by jcohenadad** [comment]
MTS segmentations fixed in #43
