### ISSUE TITLE
cmrra where is minimally one data point over dataset?

### ISSUE THREAD

**Issue by renelabounek** [spine-generic/data-multi-subject#52]
I have checked cmrra (6 subjects submitted) and cmrrb (7 subjects submitted) dots over manuscript graphs and it looks like one subject was mostly excluded from the cmrra dataset, i.e.:

figure 13 – 5 dots
figure 14 – 6 dots
figure 16 – 4-5dots not sure
figure 17 – 5 dots
figure 18 – 4 dots
figure 19 – 5 dots

I have not found any poor data quality report for the cmrra dataset at: https://github.com/spine-generic/data-multi-subject/labels/data-quality
Nor in figure legengs or manuscript Results text, that some cmrra data point was excluded from results for any above mentioned figure. That is why I consider it as strange.

Only issue I remember about the cmrra acquisition, there was a tiny female sub05 (height 152cm, weight 47kg) where many axial scans had overexposed brightness outside SC? We discussed this after acquisition and kept the data point in the dataset as the real life issue. Or was there some other issue related to the 3D T1 scan (i.e. figure 13 5 dots versus figure 14 6 dots)?

Julien and Alexandru wrote us an email that strong automatic defacing corrupted 3D T1w and 3D T2w scans for sub-04 and sub-05 in cmrra dataset. We defaced them manually and send manually defaced scans to them. That could be other reason how some data points could be lost for the cmrra dataset.

Thanks for the tracking-back and the  feedback,
Rene

**Comment by jcohenadad** [comment]
there is no cmrra subject excluded from 830992b: https://github.com/spine-generic/data-multi-subject/blob/master/exclude.yml

maybe the dots overlap? it would be more reliable to look at the actual csv file from the [latest results](https://github.com/spine-generic/data-multi-subject/releases/download/r20200917/results_r20200917.zip)

**Comment by renelabounek** [comment]
Ok, I will double-check it tomorrow. Thanks

**Comment by renelabounek** [comment]
Very sorry for the cunfusion, I hve double-check all result .csv files and 6 datapoints are in all .csv files for the cmrra dataset.
Rene
