### ISSUE TITLE
Gender should be changed for sex

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/data-multi-subject#68]
https://github.com/spine-generic/data-multi-subject/blob/2bfd18a4e18039433b1e07642dbadf3b5a3ce5b9/participants.json#L7

**Comment by alexfoias** [comment]
@kousu Can I create a branch ? and open a PR ? or directly push the change?

**Comment by kousu** [comment]
The .json files are not annexed. You can tell because you can see them here in the Github UI, and you can just edit them right there with Github's Edit button, and that'll make PR.

**Comment by kousu** [comment]
Like:

This is an annex pointer:

https://github.com/spine-generic/data-multi-subject/blob/2bfd18a4e18039433b1e07642dbadf3b5a3ce5b9/sub-vuiisAchieva01/dwi/sub-vuiisAchieva01_dwi.nii.gz#L1

this is a regular file in git:

https://github.com/spine-generic/data-multi-subject/blob/2bfd18a4e18039433b1e07642dbadf3b5a3ce5b9/sub-vuiisAchieva01/dwi/sub-vuiisAchieva01_dwi.json#L1-L10
