### ISSUE TITLE
Source of manual segmentation/correction of CSF

### ISSUE THREAD

**Issue by leandervaneekelen** [spine-generic/data-multi-subject#71]
All subjects with `_T2w_csf-manual.nii.gz` seem to be missing their accompanying JSON sidecars where the author of the segmentation is documented. Do we know who did these/how they were made? Manual correction of `sct_propseg` output?

For reference, the subjects with `csf-manual` files:

<details>
<summary>Click</summary>

```./sub-cmrrb03/anat/sub-cmrrb03_T2w_csfseg-manual.nii.gz
./sub-perform02/anat/sub-perform02_T2w_csfseg-manual.nii.gz
./sub-barcelona05/anat/sub-barcelona05_T2w_csfseg-manual.nii.gz
./sub-nottwil03/anat/sub-nottwil03_T2w_csfseg-manual.nii.gz
./sub-tokyoIngenia05/anat/sub-tokyoIngenia05_T2w_csfseg-manual.nii.gz
./sub-tokyoIngenia06/anat/sub-tokyoIngenia06_T2w_csfseg-manual.nii.gz
./sub-pavia04/anat/sub-pavia04_T2w_csfseg-manual.nii.gz
./sub-geneva04/anat/sub-geneva04_T2w_csfseg-manual.nii.gz
./sub-nottwil01/anat/sub-nottwil01_T2w_csfseg-manual.nii.gz
./sub-nottwil04/anat/sub-nottwil04_T2w_csfseg-manual.nii.gz

**Comment by jcohenadad** [comment]
@charleygros do you remember who it was? maybe you or Anthime?

**Comment by charleygros** [comment]
> @charleygros do you remember who it was? maybe you or Anthime?

Oh, It was actually me, manual correction of `sct_propseg` output!

**Comment by jcohenadad** [comment]
@alexfoias can you pls create and upload the JSON files for these? thanks!

**Comment by alexfoias** [comment]
@leandervaneekelen I'm taking care of it.
