### ISSUE TITLE
Make it more explicit in the doc that git-annex 8 is required

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/data-multi-subject#80]
More context: https://github.com/spine-generic/data-multi-subject/issues/78#issuecomment-817951875

**Comment by kousu** [comment]
I wish there was a way we could script this. `.git/hooks/` could do it, except (for good reason) you can't force-install git hooks onto peoples' systems without their consent, so we would just end up replacing the easily missable "check 'git annex version'" with the easily missable "run `ln -s ../hooks .git/hooks`". I suppose we could provide a small downloader script but I am wary of that slippery slope.
