### ISSUE TITLE
Substitute dash with n/a in the participants.tsv

### ISSUE THREAD

**Issue by mpompolas** [spine-generic/data-multi-subject#89]
Same issue was encountered with sct-testing-large.

See: https://github.com/ivadomed/ivadomed/issues/796

**Comment by alexfoias** [comment]
yes indeed. I will fix it.

**Comment by alexfoias** [comment]
@kousu should I work from my fork or is it better to create a branch on this repo ? I think we had issues in the past as in [here](https://github.com/spine-generic/data-multi-subject/pull/77).

**Comment by kousu** [comment]
Please work in a branch here.

**Comment by alexfoias** [comment]
this issue was already addressed. closing it.
